### ISSUE TITLE
Getting error while running project on Windows os

### ISSUE THREAD

**Issue by UnmeshK25** [CharlBest/nean-stack-starter#185]
I am getting following errors while running (executing the "npm start" command )the nean stack project on windows platform.
can you please provide the solution on this issue or provide the steps or commands 
![Error](https://user-images.githubusercontent.com/23443605/67886483-bfef0900-fb06-11e9-93d0-ae5cc3d06023.JPG)

Error:

node --max_semi_space_size=2 --max_old_space_size=256 dist/server/web/web.bundle.js
webpack-internal:///37:40
            logger_1.logger.error(error);
                            ^
TypeError: Cannot read property 'error' of undefined

**Comment by CharlBest** [comment]
Hi @UnmeshK25. Thank you for logging this issue. This is now fixed but you will still need to provide the environment variables when running your node project. I use a process manager called pm2 in production and in there I can specify NODE_ENV etc when running the project. When I run it locally it goes and looks in the environments file for default values.

**Comment by CharlBest** [comment]
Also try running "npm run dev" rather than "npm start" as that is the command to run when running in production. I have updated the README to reflect that. Sorry about the confusion. npm run dev will use default environment variables and everything should just work. Let me know if you want further help.
